name: general_weather
description: General Weather Feature
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  dartz:
  dropdown_search:
  equatable:
  flutter_bloc:
  flutter_secure_storage:
  flutter_svg:
  get_it:
  http:
  injectable:
  json_serializable:
  lottie:
  path:
  url_launcher:
  json_annotation:
  shared_design_components:
    path: ../../shared_design_components

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^3.0.0
  injectable_generator: